//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.03 at 06:10:43 PM EEST 
//


package org.sonar.plugins.powershell.issues;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sonar.plugins.powershell.issues package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sonar.plugins.powershell.issues
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Objects }
     * 
     */
    public Objects createObjects() {
        return new Objects();
    }

    /**
     * Create an instance of {@link Objects.Object }
     * 
     */
    public Objects.Object createObjectsObject() {
        return new Objects.Object();
    }

    /**
     * Create an instance of {@link Objects.Object.Property }
     * 
     */
    public Objects.Object.Property createObjectsObjectProperty() {
        return new Objects.Object.Property();
    }

}
