//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 08:22:06 PM EEST 
//


package org.sonar.plugins.powershell.ast;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndOffset_QNAME = new QName("", "EndOffset");
    private final static QName _TokenFlags_QNAME = new QName("", "TokenFlags");
    private final static QName _CType_QNAME = new QName("", "CType");
    private final static QName _StartOffset_QNAME = new QName("", "StartOffset");
    private final static QName _StartColumnNumber_QNAME = new QName("", "StartColumnNumber");
    private final static QName _StartLineNumber_QNAME = new QName("", "StartLineNumber");
    private final static QName _Kind_QNAME = new QName("", "Kind");
    private final static QName _EndLineNumber_QNAME = new QName("", "EndLineNumber");
    private final static QName _Value_QNAME = new QName("", "Value");
    private final static QName _Text_QNAME = new QName("", "Text");
    private final static QName _EndColumnNumber_QNAME = new QName("", "EndColumnNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link Tokens }
     * 
     */
    public Tokens createTokens() {
        return new Tokens();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EndOffset")
    public JAXBElement<Short> createEndOffset(Short value) {
        return new JAXBElement<Short>(_EndOffset_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TokenFlags")
    public JAXBElement<String> createTokenFlags(String value) {
        return new JAXBElement<String>(_TokenFlags_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CType")
    public JAXBElement<String> createCType(String value) {
        return new JAXBElement<String>(_CType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StartOffset")
    public JAXBElement<Short> createStartOffset(Short value) {
        return new JAXBElement<Short>(_StartOffset_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StartColumnNumber")
    public JAXBElement<Byte> createStartColumnNumber(Byte value) {
        return new JAXBElement<Byte>(_StartColumnNumber_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StartLineNumber")
    public JAXBElement<Byte> createStartLineNumber(Byte value) {
        return new JAXBElement<Byte>(_StartLineNumber_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Kind")
    public JAXBElement<String> createKind(String value) {
        return new JAXBElement<String>(_Kind_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EndLineNumber")
    public JAXBElement<Byte> createEndLineNumber(Byte value) {
        return new JAXBElement<Byte>(_EndLineNumber_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EndColumnNumber")
    public JAXBElement<Byte> createEndColumnNumber(Byte value) {
        return new JAXBElement<Byte>(_EndColumnNumber_QNAME, Byte.class, null, value);
    }

}
