//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.07 at 10:33:37 PM EEST 
//


package org.sonar.plugins.powershell.ast;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Token" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TokenFlags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Kind" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="StartLineNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="CType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EndLineNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="StartOffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="EndOffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="StartColumnNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="EndColumnNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="complexity" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "token"
})
@XmlRootElement(name = "Tokens")
public class Tokens {

    @XmlElement(name = "Token")
    protected List<Tokens.Token> token;
    @XmlAttribute(name = "complexity")
    protected Integer complexity;

    /**
     * Gets the value of the token property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the token property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToken().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tokens.Token }
     * 
     * 
     */
    public List<Tokens.Token> getToken() {
        if (token == null) {
            token = new ArrayList<Tokens.Token>();
        }
        return this.token;
    }

    /**
     * Gets the value of the complexity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getComplexity() {
        return complexity;
    }

    /**
     * Sets the value of the complexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setComplexity(Integer value) {
        this.complexity = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TokenFlags" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Kind" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="StartLineNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="CType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EndLineNumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="StartOffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="EndOffset" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="StartColumnNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="EndColumnNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "text",
        "value",
        "tokenFlags",
        "kind",
        "startLineNumber",
        "cType",
        "endLineNumber",
        "startOffset",
        "endOffset",
        "startColumnNumber",
        "endColumnNumber"
    })
    public static class Token {

        @XmlElement(name = "Text", required = true)
        protected String text;
        @XmlElement(name = "Value", required = true)
        protected String value;
        @XmlElement(name = "TokenFlags", required = true)
        protected String tokenFlags;
        @XmlElement(name = "Kind", required = true)
        protected String kind;
        @XmlElement(name = "StartLineNumber")
        protected int startLineNumber;
        @XmlElement(name = "CType", required = true)
        protected String cType;
        @XmlElement(name = "EndLineNumber")
        protected int endLineNumber;
        @XmlElement(name = "StartOffset")
        protected int startOffset;
        @XmlElement(name = "EndOffset")
        protected int endOffset;
        @XmlElement(name = "StartColumnNumber")
        protected int startColumnNumber;
        @XmlElement(name = "EndColumnNumber")
        protected int endColumnNumber;

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the tokenFlags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTokenFlags() {
            return tokenFlags;
        }

        /**
         * Sets the value of the tokenFlags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTokenFlags(String value) {
            this.tokenFlags = value;
        }

        /**
         * Gets the value of the kind property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKind() {
            return kind;
        }

        /**
         * Sets the value of the kind property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKind(String value) {
            this.kind = value;
        }

        /**
         * Gets the value of the startLineNumber property.
         * 
         */
        public int getStartLineNumber() {
            return startLineNumber;
        }

        /**
         * Sets the value of the startLineNumber property.
         * 
         */
        public void setStartLineNumber(int value) {
            this.startLineNumber = value;
        }

        /**
         * Gets the value of the cType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCType() {
            return cType;
        }

        /**
         * Sets the value of the cType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCType(String value) {
            this.cType = value;
        }

        /**
         * Gets the value of the endLineNumber property.
         * 
         */
        public int getEndLineNumber() {
            return endLineNumber;
        }

        /**
         * Sets the value of the endLineNumber property.
         * 
         */
        public void setEndLineNumber(int value) {
            this.endLineNumber = value;
        }

        /**
         * Gets the value of the startOffset property.
         * 
         */
        public int getStartOffset() {
            return startOffset;
        }

        /**
         * Sets the value of the startOffset property.
         * 
         */
        public void setStartOffset(int value) {
            this.startOffset = value;
        }

        /**
         * Gets the value of the endOffset property.
         * 
         */
        public int getEndOffset() {
            return endOffset;
        }

        /**
         * Sets the value of the endOffset property.
         * 
         */
        public void setEndOffset(int value) {
            this.endOffset = value;
        }

        /**
         * Gets the value of the startColumnNumber property.
         * 
         */
        public int getStartColumnNumber() {
            return startColumnNumber;
        }

        /**
         * Sets the value of the startColumnNumber property.
         * 
         */
        public void setStartColumnNumber(int value) {
            this.startColumnNumber = value;
        }

        /**
         * Gets the value of the endColumnNumber property.
         * 
         */
        public int getEndColumnNumber() {
            return endColumnNumber;
        }

        /**
         * Sets the value of the endColumnNumber property.
         * 
         */
        public void setEndColumnNumber(int value) {
            this.endColumnNumber = value;
        }

    }

}
