//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 08:22:06 PM EEST 
//


package org.sonar.plugins.powershell.ast;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Text"/>
 *         &lt;element ref="{}Value"/>
 *         &lt;element ref="{}TokenFlags"/>
 *         &lt;element ref="{}Kind"/>
 *         &lt;element ref="{}StartLineNumber"/>
 *         &lt;element ref="{}CType"/>
 *         &lt;element ref="{}EndLineNumber"/>
 *         &lt;element ref="{}StartOffset"/>
 *         &lt;element ref="{}EndOffset"/>
 *         &lt;element ref="{}StartColumnNumber"/>
 *         &lt;element ref="{}EndColumnNumber"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "text",
    "value",
    "tokenFlags",
    "kind",
    "startLineNumber",
    "cType",
    "endLineNumber",
    "startOffset",
    "endOffset",
    "startColumnNumber",
    "endColumnNumber"
})
@XmlRootElement(name = "Token")
public class Token {

    @XmlElement(name = "Text", required = true)
    protected String text;
    @XmlElement(name = "Value", required = true)
    protected String value;
    @XmlElement(name = "TokenFlags", required = true)
    protected String tokenFlags;
    @XmlElement(name = "Kind", required = true)
    protected String kind;
    @XmlElement(name = "StartLineNumber")
    protected byte startLineNumber;
    @XmlElement(name = "CType", required = true)
    protected String cType;
    @XmlElement(name = "EndLineNumber")
    protected byte endLineNumber;
    @XmlElement(name = "StartOffset")
    protected short startOffset;
    @XmlElement(name = "EndOffset")
    protected short endOffset;
    @XmlElement(name = "StartColumnNumber")
    protected byte startColumnNumber;
    @XmlElement(name = "EndColumnNumber")
    protected byte endColumnNumber;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the tokenFlags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenFlags() {
        return tokenFlags;
    }

    /**
     * Sets the value of the tokenFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenFlags(String value) {
        this.tokenFlags = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKind(String value) {
        this.kind = value;
    }

    /**
     * Gets the value of the startLineNumber property.
     * 
     */
    public byte getStartLineNumber() {
        return startLineNumber;
    }

    /**
     * Sets the value of the startLineNumber property.
     * 
     */
    public void setStartLineNumber(byte value) {
        this.startLineNumber = value;
    }

    /**
     * Gets the value of the cType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCType() {
        return cType;
    }

    /**
     * Sets the value of the cType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCType(String value) {
        this.cType = value;
    }

    /**
     * Gets the value of the endLineNumber property.
     * 
     */
    public byte getEndLineNumber() {
        return endLineNumber;
    }

    /**
     * Sets the value of the endLineNumber property.
     * 
     */
    public void setEndLineNumber(byte value) {
        this.endLineNumber = value;
    }

    /**
     * Gets the value of the startOffset property.
     * 
     */
    public short getStartOffset() {
        return startOffset;
    }

    /**
     * Sets the value of the startOffset property.
     * 
     */
    public void setStartOffset(short value) {
        this.startOffset = value;
    }

    /**
     * Gets the value of the endOffset property.
     * 
     */
    public short getEndOffset() {
        return endOffset;
    }

    /**
     * Sets the value of the endOffset property.
     * 
     */
    public void setEndOffset(short value) {
        this.endOffset = value;
    }

    /**
     * Gets the value of the startColumnNumber property.
     * 
     */
    public byte getStartColumnNumber() {
        return startColumnNumber;
    }

    /**
     * Sets the value of the startColumnNumber property.
     * 
     */
    public void setStartColumnNumber(byte value) {
        this.startColumnNumber = value;
    }

    /**
     * Gets the value of the endColumnNumber property.
     * 
     */
    public byte getEndColumnNumber() {
        return endColumnNumber;
    }

    /**
     * Sets the value of the endColumnNumber property.
     * 
     */
    public void setEndColumnNumber(byte value) {
        this.endColumnNumber = value;
    }

}
